### ISSUE TITLE
formOptions should be part of returned data

### ISSUE THREAD

**Issue by digicos** [vue-generators/vue-form-generator-docs#7]
the example on this [page](https://icebob.gitbooks.io/vueformgenerator/content/usage.html) has formOptions as a nested element of "schema" element. This throws an error on rendering. When I changed it to be a part of object returned from data() function, the component rendered successfully.

`formOptions: {
            validateAfterLoad: true,
            validateAfterChanged: true,
            fieldIdPrefix: 'user-'
}`

checked the above issue at this [documentation  page](https://vue-generators.gitbook.io/vue-generators/usage) as well

**Comment by zoul0813** [comment]
The second link is correct, and works as expected.

The first link is the old documentation, and is no longer supported or updated.

The VFG README.md on the [GitHub repo](https://github.com/vue-generators/vue-form-generator) points to the latest documentation
